apiVersion: v1
kind: Service
metadata:
  name: influxdb-ip-service
spec:
  type: ClusterIP
  selector: 
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: prometheus
          image: influxdb:1.8
          ports:
            - name: http
              containerPort: 8086
              protocol: tcp
            - containerPort: 2003
          volumeMounts:
            - name: data
              mountPath: /influxdb/
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: INFLUXDB_DB
              value: "phobos-db"
      volumes:
        - name: data
          emptyDir: {}